<?php


namespace app\admin\controller;
use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends  BaseController
{
    public $adminUser = null;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//        if(!$this->isLogin()){
//            return $this->redirect(url('login/index'),302);
//        }


    }

    protected  function isLogin(){
        $this->adminUser = session(config('admin.session_admin'));
        if(empty($this->adminUser)){
            return false;
        }
        return true;
    }


    protected function redirect(...$args){
        throw  new HttpResponseException(redirect(...$args));
     }

}